name: binary-mixture-publication

channels:
  - simonboothroyd
  - openeye
  - conda-forge
  - defaults

dependencies:

  - python
  - pip

  - openeye-toolkits

  # Common dependencies
  - tqdm
  - seaborn

  # vdW fitting
  - nonbonded >= 0.0.1b1
  - openmm >=7.5.1
  - distributed ==2.30.1
  - mdtraj ==1.9.4
